# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ruby:2.5.1
        environment:
          DB_HOST: "localhost"
          DB_PORT: 5432
          DB_USER: "postgres"
          DB_PASS: ""
          DB_NAME: "cocoremo"
      - image: postgres:9.6

    working_directory: ~/cocoremo

    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler version?
          command: bundle -v

      - run:
          name: install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
              && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
              && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: install node
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | bash - \
              && apt-get install -y nodejs

      - run:
          name : install yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
              && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
              && apt-get update \
              && apt-get install -y yarn

      # Bundle dependencies setup
      - restore_cache:
          keys:
            - v1-bundle-dependencies-{{ checksum "Gemfile.lock" }}
              # fallback to using the latest cache if no exact match is found
            - v1-bundle-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-bundle-dependencies-{{ checksum "Gemfile.lock" }}

      # Yarn dependencies setup
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v1-yarn-dependencies-

      - run:
          name: install yarn dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-dependencies-{{ checksum "yarn.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              $TEST_FILES
          environment:
            COVERAGE_DIR: /tmp/test-results/coverage

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
